[package]
name = "dkg-webserver"
version = "0.1.0"
authors = ["Daniel <daniel@netsmile.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
fs_extra = "1.1.0"
